---
title: Excercise 1
author: R package build
date: '2022-02-21'
slug: feb21st
categories: []
tags: []
---

```{r}
library(tidyverse)
catlovers <- "https://raw.githubusercontent.com/dearbharat/tidyverse/main/cat-lovers.csv"

cat_lovers <- read_csv(catlovers)

```

```{r}
glimpse(catlovers)
cat_lovers %>%
  summarise(mean_cats = mean(number_of_cats))

```

```{r}

cat_lovers %>%
  mutate(number_of_cats = case_when(
    name == "Ginger Clark" ~ 2,
    name == "Doug Bass"    ~ 3,
    TRUE                   ~ as.numeric(number_of_cats)
    )) %>%
  summarise(mean_cats = mean(number_of_cats))

```


### Numeric Data Summarization 
```{r}

cat_lovers %>%
  mutate(
    number_of_cats = case_when(
      name == "Ginger Clark" ~ "2",
      name == "Doug Bass"    ~ "3",
      TRUE                   ~ number_of_cats
      ),
    number_of_cats = as.numeric(number_of_cats)
    ) %>%
  summarise(mean_cats = mean(number_of_cats))
#

```

```{r}

cat_lovers <- cat_lovers %>%
  mutate(
    number_of_cats = case_when(
      name == "Ginger Clark" ~ "2",
      name == "Doug Bass"    ~ "3",
      TRUE                   ~ number_of_cats
      ),
    number_of_cats = as.numeric(number_of_cats)
    )

```

```{r}



```

-   `c(1, 1L, "C")`

```{r}
c(1, 1L, "C")
```

```{r}
1
1L
"C"
```

```{r}
## int int char 
```

-   `c(1L / 0, "A")`

```{r}
c(1L / 0, "A")
```

```{r}
typeof(1L)
typeof(0)
typeof(1L/0)
typeof("A")
```

```{r}
#integer , double 
```

-   `c(1:3, 5)`

```{r}
c(1:3, 5)
```

```{r}
typeof(1:3)
typeof(5)
```

```{r}
#double character 
```

-   `c(3, "3+")`

```{r}
c(3, "3+")
```

```{r}
typeof(3)
typeof("3+")
```

```{r}
#logical , logical 
```

-   `c(NA, TRUE)`

```{r}
c(NA, TRUE)
```

```{r}
typeof(NA)
typeof(TRUE)
```

```{r}
#logical logical 
```